services:
  - type: web
    name: item-backend
    env: ruby
    preBuildCommand: apt-get update && apt-get install -y build-essential libpq-dev # Ensure build tools and PostgreSQL libraries are installed
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase: item-backend-db

databases:
  - name: item-backend-db
    plan: free
    engine: postgres
    version: 13
